[build]
  publish = "public"
  command = "npm run build:netlify"
[context.production]
  environment ={  KONTENT_PROJECT_ID = "c29b3b24-a622-0004-6ae7-91e38f9efca0", KONTENT_LANGUAGE_CODENAMES = "en-US, cs-CZ" }
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "14.17.5"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
